### ISSUE TITLE
ValueError: unknown clause || DRS @ ('b5', 'b2')

### ISSUE THREAD

**Issue by dhgoratela** [RikVN/Neural_DRS#3]
Hi,
I am trying to implement DRS (with Marian only) on my ubuntu 18.04 LTS GCP instance with 8 CPU cores and no GPU.
The essential packages have been installed and I was able to create a CPU build using setup script in Neural_DRS/src/ 
My python version being used is 2.7
While I am trying to run unit_tests.sh for Marian commands only (Commented the commands for OpenNMT), the test works fine until I get the below error..

---- previous results---- followed by below--
# Main Results #
All shown number are micro-averages calculated over 20 DRS-pairs
Matching clauses: 0
Precision: 0.0
Recall   : 0.0
F-score  : 0.0

Detailed precision, recall, F-score
Prec, rec, F1 operators: 0.0, 0.0, 0.0
Prec, rec, F1 roles: 0.0, 0.0, 0.0
Prec, rec, F1 concepts: 0.0, 0.0, 0.0
Prec, rec, F1 nouns: 0.0, 0.0, 0.0
Prec, rec, F1 verbs: 0.0, 0.0, 0.0
Prec, rec, F1 adjectives: 0.0, 0.0, 0.0
Prec, rec, F1 adverbs: 0.0, 0.0, 0.0
Prec, rec, F1 events: 0.0, 0.0, 0.0
Smart F-score concepts: 0.0
Total processing time: 0.1501 sec
/home/d_goratela/.local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1920: RuntimeWarning: invalid value encountered in multiply
  lower_bound = self.a * scale + loc
/home/d_goratela/.local/lib/python2.7/site-packages/scipy/stats/_distn_infrastructure.py:1921: RuntimeWarning: invalid value encountered in multiply
  upper_bound = self.b * scale + loc

Test reproducing the F-scores for output files in the output/ folder
Traceback (most recent call last):
  File "/home/d_goratela/Neural_DRS/DRS_parsing/evaluation/counter.py", line 836, in <module>
    main(args)
  File "/home/d_goratela/Neural_DRS/DRS_parsing/evaluation/counter.py", line 761, in main
    clauses_gold_list, original_gold = get_clauses(args.f2, signature, args.ill)
  File "/home/d_goratela/Neural_DRS/DRS_parsing/evaluation/counter.py", line 209, in get_clauses
    raise ValueError(e)
ValueError: unknown clause || DRS @ ('b5', 'b2')

Any help on why we get this value error?

Is it due to the scipy version? 
The scipy version is not specified in requirements, hence it takes the recent version (1.4.1). However, the scipy version while committing setup.sh file was (1.3.3)..

**Comment by dhgoratela** [comment]
FYI I tried with the lower scipy version, I still got the same error..

**Comment by dhgoratela** [comment]
Issue gets resolved with latest commit (d74defaf64007dbeff7ac7025495eee17fba8ee1)
